# Generated by Django 3.0.8 on 2020-07-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='tittle',
            new_name='title',
        ),
    ]
